### ISSUE TITLE
Timing bug

### ISSUE THREAD

**Issue by alexandre-g** [rolandleth/LTHRadioButton#6] opened 2018-06-19 07:47 UTC
Hi,

I've found a weird animation bug with this control. Basically, with each view controller rotation, the animation takes a little longer to start animating.

So for eg. after initial load - animations starts right away, no matter how many times you toggle.
After first rotation takes ~0.2s to start animationg
After second ~0.4s etc

I didn't have enough core animation knowledge nor time to resolve the issue, but found that commenting all the `.beginTime`s "fixes it", but obviously ruins the animation timing.

**Comment by rolandleth** [comment] 2018-06-20 08:15
Hey, @alexandre-g,

Thanks, I'll look into it!

**Comment by rolandleth** [comment] 2018-06-20 08:17
I'm not sure I get it. What does "view controller rotation" mean? Literally rotate your phone from one orientation to another? I didn't manage to reproduce it on the demo app, could you, please?

**Comment by alexandre-g** [comment] 2018-06-20 13:57
Hey thanks for looking into it.
Yeah, that's what I mean by rotation.
It's not happening for me on the sample project also. Tried to put the radio button into the same kind of view structure that I have it in on the project but couldn't reproduce. Will try to single it out in the project when I get a bit more time and let you know.

**Comment by rolandleth** [comment] 2018-06-20 13:58
Cool, good luck and let me know 💪🏻

**Comment by rolandleth** [comment] 2018-08-19 12:07
Hey, @alexandre-g, 


Any luck? Or can we close this?

**Comment by alexandre-g** [comment] 2018-08-20 04:38
Didn't get to the end of it unfortunately. I have these radio buttons shown inside a modal dialog that's presented over a view controller with a `WKWebView` inside.
Modal is set up with these options:
```
modalPresentationStyle = .overFullScreen
modalTransitionStyle = .crossDissolve
```
So buttons don't have the described issue when:
- I present modal as a normal VC
- I do not programmatically add the `WKWebView` to parent VC

They still do have the issue when:
- `WKWebView` is set to hidden
- `WKWebView` is removed from view after a delay (not deinitted though as has strong reference)

I was also testing in a large ObjC view controller, so it could potentially not be the `WKWebView` at all but something else that simply didn't blow up because some messages were sent to nil.

If you have the time I suggest trying the same setup (modal over a vc with webview) and see if the issue happens after a few rotations (the more rotations the more obvious it is, won't miss it at > 15)

A bit hard to see the delay as can't see when I clicked - but imagine i'm clicking straight away
And ignore the weird simulator shaking
![2018-08-20 14 35 55](https://user-images.githubusercontent.com/9635561/44320625-85abc580-a486-11e8-964e-8a33ff25cdbe.gif)

**Comment by rolandleth** [comment] 2018-08-20 05:38
Hey,


Thanks for the quick reply! Sadly, I can't reproduce it. Attached is the code and the clip. Same thing happens if I remove the webView from the `view`.

<img width="573" alt="screenshot 2018-08-20 at 08 34 07" src="https://user-images.githubusercontent.com/1858700/44322001-deae3600-a453-11e8-8936-9a7f5aee9cab.png">

![1](https://user-images.githubusercontent.com/1858700/44322023-f38ac980-a453-11e8-924f-061959f4f842.gif)

**Comment by alexandre-g** [comment] 2018-08-20 05:48
Are you rotating? Issue happens only after you rotate a few times. If you are, I'll try get some time tonight to try reproduce in the sample project

**Comment by rolandleth** [comment] 2018-08-20 05:51
In the video I did not, but I tried it now, both by rotating before using the button and after + using it again — still no issue.

**Comment by alexandre-g** [comment] 2018-08-20 07:21
Ok spent another half an hour on this and think I found the bug. 
See the description and the commit on the same issue for details: https://github.com/airbnb/lottie-ios/pull/618
Placing the following code and using `currentLayerTime` instead of `CACurrentMediaTime()` wherever it's used fixed the issue for me.
```
let currentTime            = CACurrentMediaTime()
let currentLayerTime       = layer.convertTime(currentTime, from: nil)
```

I suppose the reason the webview had an effect on it is because taking a snapshot of one is quite time consuming!

PS I am using this code for snapshotting
```
+ (UIImage*) snapRect:(CGRect)rect inView:(UIView*)view {
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(rect.size.width, rect.size.height), YES, UIScreen.mainScreen.scale);

    CGRect snapFrame = CGRectMake(-rect.origin.x, -rect.origin.y, view.width, view.height);
    [view drawViewHierarchyInRect:snapFrame afterScreenUpdates:YES];
    UIImage* snapshotImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return snapshotImage;
}
```

**Comment by rolandleth** [comment] 2018-08-20 08:13
Awesome, thanks a lot for your help! Could you test the new commit before I issue a new pod version, please? I'd like to make sure it's all good, since I couldn't reproduce this on my machine.

**Closed as completed** 2018-08-20 08:12 UTC

**Comment by alexandre-g** [comment] 2018-08-20 08:23
No worries, glad to help. Just checked and it's all working.

**Comment by rolandleth** [comment] 2018-08-20 08:23
Awesome, thanks again and have a great week!
